### ISSUE TITLE
Is it possible to "Bring your own Router"?

### ISSUE THREAD

**Issue by polds** [cardinalby/hureg#1]
More of a question than anything. I'd like to utilize some `chi` middleware, but it seems like middleware need to be initialized before a Huma instance is created. But basically I'm wondering if something like this is possible with Hureg:

```golang
	mux.Group(func(r chi.Router) {
		r.Use(middleware.Logger)
		
		api = api.
			AddBasePath("/health").
			AddOpHandler(op.AddTags("health-checking", "system"))

		// GET /health - Check the health of the service.
		hureg.Register(api, checkHealth, h.CheckHealth)
	})
```

At the moment it doesn't seem like Chi is able to get in front of anything.

**Comment by cardinalby** [comment]
Hi! That's a good question :)

1. The Huma's idiomatic way would be rewrite the middleware to Huma format so that it can be used for specific operations (or groups with Hureg) since router-specific middlewares can only stay before Huma. If you want to use only this particular middleware, maybe it's the easiest way.

2. Another way is try to implement "chi middleware" -> "huma middleware" mapper (kind of opposite to what is done in humachi adapter). You will need to reconstruct http.Request and writter (they are hidden in the private fields `chiContext` in `humachi` package). Looks a bit clumsy, not sure all the data can be extracted from `huma.Context` using the public methods.

3. Hureg way. By your request I added a new `APIGen.ReplaceHumaAPI` method, so you can [do the trick](https://github.com/cardinalby/hureg/blob/master/docs/huma_api_per_group.md) with a Huma instance defined for a particular Hureg group

P.S. Use Hureg `v1.0.2` and put `/health` in place of `/dog` in my example :)

**Comment by cardinalby** [comment]
@polds Let me know if it helped you and the issue can be closed

**Comment by polds** [comment]
Hey sorry, I haven't been able to give it a try. I'm trying it now. Thanks for being faster than me in responding!

**Comment by polds** [comment]
I just gave it a try and the `v1.0.2` fits what I've been needing perfectly! Thank you!
